CLASS zcl_stkoes DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_stkoes IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.
    out->WRITE( 'Test' ).
  ENDMETHOD.

ENDCLASS.
